import Head from "next/head";
import Footer from "../components/Footer";
import AboutMe from "../views/about/AboutMe";
import HeroPage from "../views/HeroPage/HeroPage";
import Projects from "../views/projects/Projects";
import Navbar from "../components/Navbar"
import { ElevationScroll } from "../components/Navbar";
import Skills from "../views/skills/Skills";
import Contacts from "../views/contacts/Contacts";
import Services from "../views/services/Services";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Swetha..{`${"</>"}`}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.jpg' />
			</Head>
			<main className='main'>
				<Navbar />
				<HeroPage />
				<div className="section">
					<AboutMe />
					<Services />
					<Projects />
					<Contacts />
					<Footer />
				</div>
			</main>
		</div>
	);
}


// https://jacekjeznach.com/about
