import Head from "next/head";
import Footer from "../components/Footer";
import AboutMe from "../views/about/AboutMe";
import HeroPage from "../views/HeroPage/HeroPage";
import Projects from "../views/projects/Projects";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Swetha..{`${"</>"}`}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.jpg' />
			</Head>
			<main className='main'>
				{/* <Navbar /> */}
				<HeroPage />
				<div className="section">
					<Projects />
					<AboutMe />
					<Footer />
				</div>
			</main>
		</div>
	);
}
// https://jacekjeznach.com/about
