import Head from "next/head";
import Footer from "../components/Footer";
import Services from "../views/services/Services";
import Skills from "../views/skills/Skills";
import Specialization from "../views/specialization/Specialization";
import Navbar from "../components/Navbar"

export default function skills() {
	return (
		<div>
			<Head>
				<title>Swetha..{`${"</>"}`}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.jpg' />
			</Head>
			<main className='main'>
				<Navbar />
				<div className="section">
					{/* <Services /> */}
					{/* <Specialization /> */}
					<Skills />
					<Footer />
				</div>
			</main>
		</div>
	);
}
// https://jacekjeznach.com/about
